id: proxmox_lcap_cluster
  telegram_config:
  token: '6041776188:XXXXXXXXXXXXXX_RZS7xzYYYYYYYYYYYYYYYYYY'
  group_ids:
    - '-9474IIIIII'
monitor:
  check_kube_api: True
  resolve:
    - iii-xxx-yyyyyyy.abcd.com
    - iii-xxx-zzzzzzz.abcd.com
  ping:
    - 192.168.XXX.YYY
    - 192.168.XXX.ZZZ
  access:
    - "https://192.168.XXX.YYYY:6443"
